using System.Net;
using System.Net.Http.Json;
using System.Text.Json.Serialization;
using Microsoft.Extensions.Logging;

namespace Wisp.Infrastructure.ExternalCatalog.YouTube;

public sealed class YouTubeNotConfiguredException() : Exception("YouTube Data API key is not configured.");
public sealed class YouTubeQuotaExceededException(string message) : Exception(message);

public sealed record YouTubeUpload(string VideoId, string Title, DateTimeOffset PublishedAt, string Url);

public sealed class YouTubeCatalogClient(
    IHttpClientFactory httpFactory,
    YouTubeOptions options,
    ILogger<YouTubeCatalogClient> log)
{
    private const string ApiBase = "https://www.googleapis.com/youtube/v3";

    public bool IsConfigured => options.IsConfigured;

    /// Lightweight credential check — `videos.list?id=dQw4w9WgXcQ` is 1 unit and a known-public video.
    public async Task<string?> TestConnectionAsync(CancellationToken ct)
    {
        if (!options.IsConfigured) return "API key not set.";
        try
        {
            var http = httpFactory.CreateClient("Wisp.YouTube");
            using var resp = await http.GetAsync(
                $"{ApiBase}/videos?part=id&id=dQw4w9WgXcQ&key={Uri.EscapeDataString(options.ApiKey!)}", ct);
            if (resp.IsSuccessStatusCode) return null;
            var body = await resp.Content.ReadAsStringAsync(ct);
            return $"YouTube API call failed: {(int)resp.StatusCode}. {Truncate(body, 200)}";
        }
        catch (Exception ex)
        {
            return ex.Message;
        }
    }

    /// Find candidate Topic channels for an artist. Topic channels are auto-generated by
    /// YouTube from licensed music feeds — much cleaner than the artist's own channel which
    /// often mixes interviews + non-music content. Falls back to general channel matches if
    /// no Topic channel exists, so the user can still pick something.
    /// **Quota cost: 100 units per call** — `search.list` is by far the most expensive YT
    /// endpoint, so we only run this when the user explicitly tries to match.
    public async Task<IReadOnlyList<CatalogArtistCandidate>> SearchTopicChannelsAsync(
        string artistName, int limit, CancellationToken ct)
    {
        if (!options.IsConfigured) throw new YouTubeNotConfiguredException();

        var http = httpFactory.CreateClient("Wisp.YouTube");
        // Asking for "X - Topic" specifically biases toward the auto-generated music channels,
        // but YT search is fuzzy so general matches will still come through ranked lower.
        var query = $"{artistName} - Topic";
        var url = $"{ApiBase}/search?part=snippet&type=channel&maxResults={Math.Clamp(limit, 1, 10)}" +
                  $"&q={Uri.EscapeDataString(query)}&key={Uri.EscapeDataString(options.ApiKey!)}";

        using var resp = await http.GetAsync(url, ct);
        await ThrowOnQuota(resp, ct);
        resp.EnsureSuccessStatusCode();

        var body = await resp.Content.ReadFromJsonAsync<YouTubeSearchResponse>(ct);
        var items = body?.Items ?? [];

        return items
            .Where(i => i.Id?.Kind == "youtube#channel" && !string.IsNullOrEmpty(i.Id.ChannelId))
            .Select(i => new CatalogArtistCandidate(
                Source: "YouTube",
                ExternalId: i.Id!.ChannelId!,
                Name: i.Snippet?.ChannelTitle ?? i.Snippet?.Title ?? "(unknown)",
                Followers: null,
                Genres: [],
                ImageUrl: i.Snippet?.Thumbnails?.Default?.Url ?? i.Snippet?.Thumbnails?.Medium?.Url))
            .ToArray();
    }

    /// Resolve the Topic channel's "uploads" playlist and page through it.
    /// 1 quota unit per page of 50 — much cheaper than running `search.list` per artist.
    public async Task<IReadOnlyList<YouTubeUpload>> GetTopicChannelUploadsAsync(
        string channelId, CancellationToken ct, int maxItems = 200)
    {
        if (!options.IsConfigured) throw new YouTubeNotConfiguredException();
        var http = httpFactory.CreateClient("Wisp.YouTube");

        // Step 1: resolve the uploads playlist id from the channel.
        var channelUrl = $"{ApiBase}/channels?part=contentDetails&id={Uri.EscapeDataString(channelId)}" +
                         $"&key={Uri.EscapeDataString(options.ApiKey!)}";
        using var channelResp = await http.GetAsync(channelUrl, ct);
        await ThrowOnQuota(channelResp, ct);
        channelResp.EnsureSuccessStatusCode();
        var channelBody = await channelResp.Content.ReadFromJsonAsync<YouTubeChannelsResponse>(ct);
        var uploadsPlaylistId = channelBody?.Items?.FirstOrDefault()?.ContentDetails?.RelatedPlaylists?.Uploads;
        if (string.IsNullOrEmpty(uploadsPlaylistId))
        {
            log.LogWarning("YouTube: channel {ChannelId} has no uploads playlist", channelId);
            return [];
        }

        // Step 2: page through playlistItems.
        var results = new List<YouTubeUpload>();
        string? pageToken = null;
        do
        {
            var url = $"{ApiBase}/playlistItems?part=snippet,contentDetails" +
                      $"&playlistId={Uri.EscapeDataString(uploadsPlaylistId)}&maxResults=50" +
                      $"&key={Uri.EscapeDataString(options.ApiKey!)}";
            if (!string.IsNullOrEmpty(pageToken))
                url += $"&pageToken={Uri.EscapeDataString(pageToken)}";

            using var resp = await http.GetAsync(url, ct);
            await ThrowOnQuota(resp, ct);
            resp.EnsureSuccessStatusCode();
            var body = await resp.Content.ReadFromJsonAsync<YouTubePlaylistItemsResponse>(ct);
            if (body is null) break;

            foreach (var item in body.Items ?? [])
            {
                var videoId = item.ContentDetails?.VideoId ?? item.Snippet?.ResourceId?.VideoId;
                var title = item.Snippet?.Title;
                if (string.IsNullOrEmpty(videoId) || string.IsNullOrEmpty(title)) continue;

                results.Add(new YouTubeUpload(
                    VideoId: videoId,
                    Title: title,
                    PublishedAt: item.ContentDetails?.VideoPublishedAt ?? item.Snippet?.PublishedAt ?? default,
                    Url: $"https://www.youtube.com/watch?v={videoId}"));

                if (results.Count >= maxItems) return results;
            }
            pageToken = body.NextPageToken;
        } while (!string.IsNullOrEmpty(pageToken));

        log.LogInformation("YouTube: channel {ChannelId} → {Count} uploads", channelId, results.Count);
        return results;
    }

    private static async Task ThrowOnQuota(HttpResponseMessage resp, CancellationToken ct)
    {
        if (resp.StatusCode != HttpStatusCode.Forbidden) return;
        var body = await resp.Content.ReadAsStringAsync(ct);
        if (body.Contains("quotaExceeded", StringComparison.OrdinalIgnoreCase))
            throw new YouTubeQuotaExceededException("YouTube Data API daily quota exceeded.");
    }

    private static string Truncate(string s, int max) => s.Length <= max ? s : s[..max] + "…";

    // ─── DTOs ───────────────────────────────────────────────────────────

    private sealed record YouTubeSearchResponse(
        [property: JsonPropertyName("items")] YouTubeSearchItem[] Items);

    private sealed record YouTubeSearchItem(
        [property: JsonPropertyName("id")] YouTubeSearchItemId? Id,
        [property: JsonPropertyName("snippet")] YouTubeSnippet? Snippet);

    private sealed record YouTubeSearchItemId(
        [property: JsonPropertyName("kind")] string? Kind,
        [property: JsonPropertyName("channelId")] string? ChannelId);

    private sealed record YouTubeSnippet(
        [property: JsonPropertyName("title")] string? Title,
        [property: JsonPropertyName("channelTitle")] string? ChannelTitle,
        [property: JsonPropertyName("publishedAt")] DateTimeOffset? PublishedAt,
        [property: JsonPropertyName("thumbnails")] YouTubeThumbnails? Thumbnails,
        [property: JsonPropertyName("resourceId")] YouTubeResourceId? ResourceId);

    private sealed record YouTubeResourceId(
        [property: JsonPropertyName("videoId")] string? VideoId);

    private sealed record YouTubeThumbnails(
        [property: JsonPropertyName("default")] YouTubeThumbnail? Default,
        [property: JsonPropertyName("medium")] YouTubeThumbnail? Medium);

    private sealed record YouTubeThumbnail(
        [property: JsonPropertyName("url")] string? Url);

    private sealed record YouTubeChannelsResponse(
        [property: JsonPropertyName("items")] YouTubeChannel[] Items);

    private sealed record YouTubeChannel(
        [property: JsonPropertyName("contentDetails")] YouTubeChannelContent? ContentDetails);

    private sealed record YouTubeChannelContent(
        [property: JsonPropertyName("relatedPlaylists")] YouTubeRelatedPlaylists? RelatedPlaylists);

    private sealed record YouTubeRelatedPlaylists(
        [property: JsonPropertyName("uploads")] string? Uploads);

    private sealed record YouTubePlaylistItemsResponse(
        [property: JsonPropertyName("items")] YouTubePlaylistItem[] Items,
        [property: JsonPropertyName("nextPageToken")] string? NextPageToken);

    private sealed record YouTubePlaylistItem(
        [property: JsonPropertyName("snippet")] YouTubeSnippet? Snippet,
        [property: JsonPropertyName("contentDetails")] YouTubePlaylistItemContent? ContentDetails);

    private sealed record YouTubePlaylistItemContent(
        [property: JsonPropertyName("videoId")] string? VideoId,
        [property: JsonPropertyName("videoPublishedAt")] DateTimeOffset? VideoPublishedAt);
}
