using System.Net;
using System.Net.Http.Json;
using System.Text.Json.Serialization;
using Microsoft.Extensions.Logging;

namespace Wisp.Infrastructure.ExternalCatalog.YouTube;

public sealed class YouTubeNotConfiguredException() : Exception("YouTube Data API key is not configured.");
public sealed class YouTubeQuotaExceededException(string message) : Exception(message);

public sealed record YouTubeUpload(
    string VideoId,
    string Title,
    DateTimeOffset PublishedAt,
    string Url,
    string? ThumbnailUrl,
    string? Description);

public sealed record YouTubeChannelInfo(
    string ChannelId,
    string Title,
    string? Description,
    string? ThumbnailUrl,
    string? UploadsPlaylistId);

public sealed record YouTubePlaylistInfo(
    string PlaylistId,
    string Title,
    string? Description,
    string? ChannelTitle);

/// One result row from `search.list?type=video`. Discover's "Anywhere" tab
/// shows a card per hit. PublishedAt drives the secondary "x months ago"
/// label; ThumbnailUrl drives the artwork.
public sealed record YouTubeVideoHit(
    string VideoId,
    string Title,
    string ChannelTitle,
    string Url,
    string? ThumbnailUrl,
    DateTimeOffset? PublishedAt,
    string? Description);

public sealed class YouTubeCatalogClient(
    IHttpClientFactory httpFactory,
    YouTubeOptions options,
    ILogger<YouTubeCatalogClient> log)
{
    private const string ApiBase = "https://www.googleapis.com/youtube/v3";

    public bool IsConfigured => options.IsConfigured;

    /// Lightweight credential check — `videos.list?id=dQw4w9WgXcQ` is 1 unit and a known-public video.
    public async Task<string?> TestConnectionAsync(CancellationToken ct)
    {
        if (!options.IsConfigured) return "API key not set.";
        try
        {
            var http = httpFactory.CreateClient("Wisp.YouTube");
            using var resp = await http.GetAsync(
                $"{ApiBase}/videos?part=id&id=dQw4w9WgXcQ&key={Uri.EscapeDataString(options.ApiKey!)}", ct);
            if (resp.IsSuccessStatusCode) return null;
            var body = await resp.Content.ReadAsStringAsync(ct);
            return $"YouTube API call failed: {(int)resp.StatusCode}. {Truncate(body, 200)}";
        }
        catch (Exception ex)
        {
            return ex.Message;
        }
    }

    /// Find candidate Topic channels for an artist. Topic channels are auto-generated by
    /// YouTube from licensed music feeds — much cleaner than the artist's own channel which
    /// often mixes interviews + non-music content. Falls back to general channel matches if
    /// no Topic channel exists, so the user can still pick something.
    /// **Quota cost: 100 units per call** — `search.list` is by far the most expensive YT
    /// endpoint, so we only run this when the user explicitly tries to match.
    public async Task<IReadOnlyList<CatalogArtistCandidate>> SearchTopicChannelsAsync(
        string artistName, int limit, CancellationToken ct)
    {
        if (!options.IsConfigured) throw new YouTubeNotConfiguredException();

        var http = httpFactory.CreateClient("Wisp.YouTube");
        // Asking for "X - Topic" specifically biases toward the auto-generated music channels,
        // but YT search is fuzzy so general matches will still come through ranked lower.
        var query = $"{artistName} - Topic";
        var url = $"{ApiBase}/search?part=snippet&type=channel&maxResults={Math.Clamp(limit, 1, 10)}" +
                  $"&q={Uri.EscapeDataString(query)}&key={Uri.EscapeDataString(options.ApiKey!)}";

        using var resp = await http.GetAsync(url, ct);
        await ThrowOnQuota(resp, ct);
        resp.EnsureSuccessStatusCode();

        var body = await resp.Content.ReadFromJsonAsync<YouTubeSearchResponse>(ct);
        var items = body?.Items ?? [];

        return items
            .Where(i => i.Id?.Kind == "youtube#channel" && !string.IsNullOrEmpty(i.Id.ChannelId))
            .Select(i => new CatalogArtistCandidate(
                Source: "YouTube",
                ExternalId: i.Id!.ChannelId!,
                Name: i.Snippet?.ChannelTitle ?? i.Snippet?.Title ?? "(unknown)",
                Followers: null,
                Genres: [],
                ImageUrl: i.Snippet?.Thumbnails?.Default?.Url ?? i.Snippet?.Thumbnails?.Medium?.Url))
            .ToArray();
    }

    /// Free-text video search used by Discover ("Anywhere" mode). 100 quota
    /// units per call — same shape as SearchTopicChannelsAsync, just with
    /// `type=video`. Caller (DiscoverEndpoints + YouTubeQuotaTracker) is
    /// responsible for caching + budgeting; this method just talks to the
    /// API and shapes the result.
    public async Task<IReadOnlyList<YouTubeVideoHit>> SearchVideosAsync(
        string query, int limit, CancellationToken ct)
    {
        if (!options.IsConfigured) throw new YouTubeNotConfiguredException();

        var http = httpFactory.CreateClient("Wisp.YouTube");
        var url = $"{ApiBase}/search?part=snippet&type=video&maxResults={Math.Clamp(limit, 1, 25)}" +
                  $"&q={Uri.EscapeDataString(query)}&key={Uri.EscapeDataString(options.ApiKey!)}";

        using var resp = await http.GetAsync(url, ct);
        await ThrowOnQuota(resp, ct);
        resp.EnsureSuccessStatusCode();

        var body = await resp.Content.ReadFromJsonAsync<YouTubeSearchResponse>(ct);
        var items = body?.Items ?? [];

        return items
            .Where(i => !string.IsNullOrEmpty(i.Id?.VideoId))
            .Select(i => new YouTubeVideoHit(
                VideoId: i.Id!.VideoId!,
                Title: i.Snippet?.Title ?? "(untitled)",
                ChannelTitle: i.Snippet?.ChannelTitle ?? "(unknown channel)",
                Url: $"https://www.youtube.com/watch?v={i.Id.VideoId}",
                ThumbnailUrl: i.Snippet?.Thumbnails?.Medium?.Url ?? i.Snippet?.Thumbnails?.Default?.Url,
                PublishedAt: i.Snippet?.PublishedAt,
                Description: i.Snippet?.Description))
            .ToArray();
    }

    /// Resolve the Topic channel's "uploads" playlist and page through it.
    /// 1 quota unit per page of 50 — much cheaper than running `search.list` per artist.
    public async Task<IReadOnlyList<YouTubeUpload>> GetTopicChannelUploadsAsync(
        string channelId, CancellationToken ct, int maxItems = 200)
    {
        if (!options.IsConfigured) throw new YouTubeNotConfiguredException();
        var http = httpFactory.CreateClient("Wisp.YouTube");

        // Step 1: resolve the uploads playlist id from the channel.
        var channelUrl = $"{ApiBase}/channels?part=contentDetails&id={Uri.EscapeDataString(channelId)}" +
                         $"&key={Uri.EscapeDataString(options.ApiKey!)}";
        using var channelResp = await http.GetAsync(channelUrl, ct);
        await ThrowOnQuota(channelResp, ct);
        channelResp.EnsureSuccessStatusCode();
        var channelBody = await channelResp.Content.ReadFromJsonAsync<YouTubeChannelsResponse>(ct);
        var uploadsPlaylistId = channelBody?.Items?.FirstOrDefault()?.ContentDetails?.RelatedPlaylists?.Uploads;
        if (string.IsNullOrEmpty(uploadsPlaylistId))
        {
            log.LogWarning("YouTube: channel {ChannelId} has no uploads playlist", channelId);
            return [];
        }

        // Step 2: page through playlistItems.
        var results = new List<YouTubeUpload>();
        string? pageToken = null;
        do
        {
            var url = $"{ApiBase}/playlistItems?part=snippet,contentDetails" +
                      $"&playlistId={Uri.EscapeDataString(uploadsPlaylistId)}&maxResults=50" +
                      $"&key={Uri.EscapeDataString(options.ApiKey!)}";
            if (!string.IsNullOrEmpty(pageToken))
                url += $"&pageToken={Uri.EscapeDataString(pageToken)}";

            using var resp = await http.GetAsync(url, ct);
            await ThrowOnQuota(resp, ct);
            resp.EnsureSuccessStatusCode();
            var body = await resp.Content.ReadFromJsonAsync<YouTubePlaylistItemsResponse>(ct);
            if (body is null) break;

            foreach (var item in body.Items ?? [])
            {
                var videoId = item.ContentDetails?.VideoId ?? item.Snippet?.ResourceId?.VideoId;
                var title = item.Snippet?.Title;
                if (string.IsNullOrEmpty(videoId) || string.IsNullOrEmpty(title)) continue;

                results.Add(new YouTubeUpload(
                    VideoId: videoId,
                    Title: title,
                    PublishedAt: item.ContentDetails?.VideoPublishedAt ?? item.Snippet?.PublishedAt ?? default,
                    Url: $"https://www.youtube.com/watch?v={videoId}",
                    ThumbnailUrl: item.Snippet?.Thumbnails?.Medium?.Url ?? item.Snippet?.Thumbnails?.Default?.Url,
                    Description: item.Snippet?.Description));

                if (results.Count >= maxItems) return results;
            }
            pageToken = body.NextPageToken;
        } while (!string.IsNullOrEmpty(pageToken));

        log.LogInformation("YouTube: channel {ChannelId} → {Count} uploads", channelId, results.Count);
        return results;
    }

    /// Resolve a `@handle` to a channelId via channels.list?forHandle=. 1 unit.
    /// Returns the channel snippet + uploads playlist id in one call (`part=snippet,contentDetails`).
    public async Task<YouTubeChannelInfo?> GetChannelByHandleAsync(string handle, CancellationToken ct)
    {
        if (!options.IsConfigured) throw new YouTubeNotConfiguredException();
        var http = httpFactory.CreateClient("Wisp.YouTube");
        var url = $"{ApiBase}/channels?part=snippet,contentDetails&forHandle=@{Uri.EscapeDataString(handle)}" +
                  $"&key={Uri.EscapeDataString(options.ApiKey!)}";
        return await FetchSingleChannelAsync(http, url, ct);
    }

    /// Resolve a legacy /user/Username to a channelId. 1 unit.
    public async Task<YouTubeChannelInfo?> GetChannelByUsernameAsync(string username, CancellationToken ct)
    {
        if (!options.IsConfigured) throw new YouTubeNotConfiguredException();
        var http = httpFactory.CreateClient("Wisp.YouTube");
        var url = $"{ApiBase}/channels?part=snippet,contentDetails&forUsername={Uri.EscapeDataString(username)}" +
                  $"&key={Uri.EscapeDataString(options.ApiKey!)}";
        return await FetchSingleChannelAsync(http, url, ct);
    }

    /// Resolve a known channelId to its snippet + uploads playlist id. 1 unit.
    public async Task<YouTubeChannelInfo?> GetChannelByIdAsync(string channelId, CancellationToken ct)
    {
        if (!options.IsConfigured) throw new YouTubeNotConfiguredException();
        var http = httpFactory.CreateClient("Wisp.YouTube");
        var url = $"{ApiBase}/channels?part=snippet,contentDetails&id={Uri.EscapeDataString(channelId)}" +
                  $"&key={Uri.EscapeDataString(options.ApiKey!)}";
        return await FetchSingleChannelAsync(http, url, ct);
    }

    /// Last-resort fallback for /c/CustomUrl — use search.list (100 units) to find the channel.
    public async Task<YouTubeChannelInfo?> SearchChannelAsync(string query, CancellationToken ct)
    {
        if (!options.IsConfigured) throw new YouTubeNotConfiguredException();
        var http = httpFactory.CreateClient("Wisp.YouTube");
        var url = $"{ApiBase}/search?part=snippet&type=channel&maxResults=1&q={Uri.EscapeDataString(query)}" +
                  $"&key={Uri.EscapeDataString(options.ApiKey!)}";
        using var resp = await http.GetAsync(url, ct);
        await ThrowOnQuota(resp, ct);
        resp.EnsureSuccessStatusCode();
        var body = await resp.Content.ReadFromJsonAsync<YouTubeSearchResponse>(ct);
        var hit = body?.Items?.FirstOrDefault(i => i.Id?.Kind == "youtube#channel" && !string.IsNullOrEmpty(i.Id.ChannelId));
        if (hit?.Id?.ChannelId is null) return null;
        return await GetChannelByIdAsync(hit.Id.ChannelId, ct);
    }

    /// Returns playlist metadata + paged items. 1 unit per page of 50.
    public async Task<(YouTubePlaylistInfo Info, IReadOnlyList<YouTubeUpload> Items)> GetPlaylistAsync(
        string playlistId, CancellationToken ct, int maxItems = 1000)
    {
        if (!options.IsConfigured) throw new YouTubeNotConfiguredException();
        var http = httpFactory.CreateClient("Wisp.YouTube");

        // Step 1: playlist metadata
        var infoUrl = $"{ApiBase}/playlists?part=snippet&id={Uri.EscapeDataString(playlistId)}" +
                      $"&key={Uri.EscapeDataString(options.ApiKey!)}";
        using var infoResp = await http.GetAsync(infoUrl, ct);
        await ThrowOnQuota(infoResp, ct);
        infoResp.EnsureSuccessStatusCode();
        var infoBody = await infoResp.Content.ReadFromJsonAsync<YouTubePlaylistsResponse>(ct);
        var pl = infoBody?.Items?.FirstOrDefault();
        if (pl is null) return (new YouTubePlaylistInfo(playlistId, playlistId, null, null), []);

        var info = new YouTubePlaylistInfo(
            playlistId,
            pl.Snippet?.Title ?? playlistId,
            pl.Snippet?.Description,
            pl.Snippet?.ChannelTitle);

        // Step 2: items (reuse the channel-uploads paging logic).
        var items = await PageThroughPlaylistItemsAsync(playlistId, maxItems, ct);
        return (info, items);
    }

    /// Reuses the channel-uploads paging path. Parameter is the playlist id (uploads or otherwise).
    public async Task<IReadOnlyList<YouTubeUpload>> PageThroughPlaylistItemsAsync(
        string playlistId, int maxItems, CancellationToken ct)
    {
        if (!options.IsConfigured) throw new YouTubeNotConfiguredException();
        var http = httpFactory.CreateClient("Wisp.YouTube");

        var results = new List<YouTubeUpload>();
        string? pageToken = null;
        do
        {
            var url = $"{ApiBase}/playlistItems?part=snippet,contentDetails" +
                      $"&playlistId={Uri.EscapeDataString(playlistId)}&maxResults=50" +
                      $"&key={Uri.EscapeDataString(options.ApiKey!)}";
            if (!string.IsNullOrEmpty(pageToken))
                url += $"&pageToken={Uri.EscapeDataString(pageToken)}";

            using var resp = await http.GetAsync(url, ct);
            await ThrowOnQuota(resp, ct);
            resp.EnsureSuccessStatusCode();
            var body = await resp.Content.ReadFromJsonAsync<YouTubePlaylistItemsResponse>(ct);
            if (body is null) break;

            foreach (var item in body.Items ?? [])
            {
                var videoId = item.ContentDetails?.VideoId ?? item.Snippet?.ResourceId?.VideoId;
                var title = item.Snippet?.Title;
                if (string.IsNullOrEmpty(videoId) || string.IsNullOrEmpty(title)) continue;

                results.Add(new YouTubeUpload(
                    VideoId: videoId,
                    Title: title,
                    PublishedAt: item.ContentDetails?.VideoPublishedAt ?? item.Snippet?.PublishedAt ?? default,
                    Url: $"https://www.youtube.com/watch?v={videoId}",
                    ThumbnailUrl: item.Snippet?.Thumbnails?.Medium?.Url ?? item.Snippet?.Thumbnails?.Default?.Url,
                    Description: item.Snippet?.Description));

                if (results.Count >= maxItems) return results;
            }
            pageToken = body.NextPageToken;
        } while (!string.IsNullOrEmpty(pageToken));

        return results;
    }

    private async Task<YouTubeChannelInfo?> FetchSingleChannelAsync(HttpClient http, string url, CancellationToken ct)
    {
        using var resp = await http.GetAsync(url, ct);
        await ThrowOnQuota(resp, ct);
        resp.EnsureSuccessStatusCode();
        var body = await resp.Content.ReadFromJsonAsync<YouTubeChannelDetailsResponse>(ct);
        var ch = body?.Items?.FirstOrDefault();
        if (ch is null || string.IsNullOrEmpty(ch.Id)) return null;
        return new YouTubeChannelInfo(
            ChannelId: ch.Id,
            Title: ch.Snippet?.Title ?? ch.Id,
            Description: ch.Snippet?.Description,
            ThumbnailUrl: ch.Snippet?.Thumbnails?.Medium?.Url ?? ch.Snippet?.Thumbnails?.Default?.Url,
            UploadsPlaylistId: ch.ContentDetails?.RelatedPlaylists?.Uploads);
    }

    private static async Task ThrowOnQuota(HttpResponseMessage resp, CancellationToken ct)
    {
        if (resp.StatusCode != HttpStatusCode.Forbidden) return;
        var body = await resp.Content.ReadAsStringAsync(ct);
        if (body.Contains("quotaExceeded", StringComparison.OrdinalIgnoreCase))
            throw new YouTubeQuotaExceededException("YouTube Data API daily quota exceeded.");
    }

    private static string Truncate(string s, int max) => s.Length <= max ? s : s[..max] + "…";

    // ─── DTOs ───────────────────────────────────────────────────────────

    private sealed record YouTubeSearchResponse(
        [property: JsonPropertyName("items")] YouTubeSearchItem[] Items);

    private sealed record YouTubeSearchItem(
        [property: JsonPropertyName("id")] YouTubeSearchItemId? Id,
        [property: JsonPropertyName("snippet")] YouTubeSnippet? Snippet);

    private sealed record YouTubeSearchItemId(
        [property: JsonPropertyName("kind")] string? Kind,
        [property: JsonPropertyName("channelId")] string? ChannelId,
        [property: JsonPropertyName("videoId")] string? VideoId);

    private sealed record YouTubeSnippet(
        [property: JsonPropertyName("title")] string? Title,
        [property: JsonPropertyName("description")] string? Description,
        [property: JsonPropertyName("channelTitle")] string? ChannelTitle,
        [property: JsonPropertyName("publishedAt")] DateTimeOffset? PublishedAt,
        [property: JsonPropertyName("thumbnails")] YouTubeThumbnails? Thumbnails,
        [property: JsonPropertyName("resourceId")] YouTubeResourceId? ResourceId);

    private sealed record YouTubeResourceId(
        [property: JsonPropertyName("videoId")] string? VideoId);

    private sealed record YouTubeThumbnails(
        [property: JsonPropertyName("default")] YouTubeThumbnail? Default,
        [property: JsonPropertyName("medium")] YouTubeThumbnail? Medium);

    private sealed record YouTubeThumbnail(
        [property: JsonPropertyName("url")] string? Url);

    private sealed record YouTubeChannelsResponse(
        [property: JsonPropertyName("items")] YouTubeChannel[] Items);

    private sealed record YouTubeChannel(
        [property: JsonPropertyName("contentDetails")] YouTubeChannelContent? ContentDetails);

    private sealed record YouTubeChannelContent(
        [property: JsonPropertyName("relatedPlaylists")] YouTubeRelatedPlaylists? RelatedPlaylists);

    private sealed record YouTubeRelatedPlaylists(
        [property: JsonPropertyName("uploads")] string? Uploads);

    private sealed record YouTubePlaylistItemsResponse(
        [property: JsonPropertyName("items")] YouTubePlaylistItem[] Items,
        [property: JsonPropertyName("nextPageToken")] string? NextPageToken);

    private sealed record YouTubePlaylistItem(
        [property: JsonPropertyName("snippet")] YouTubeSnippet? Snippet,
        [property: JsonPropertyName("contentDetails")] YouTubePlaylistItemContent? ContentDetails);

    private sealed record YouTubePlaylistItemContent(
        [property: JsonPropertyName("videoId")] string? VideoId,
        [property: JsonPropertyName("videoPublishedAt")] DateTimeOffset? VideoPublishedAt);

    private sealed record YouTubeChannelDetailsResponse(
        [property: JsonPropertyName("items")] YouTubeChannelDetail[] Items);

    private sealed record YouTubeChannelDetail(
        [property: JsonPropertyName("id")] string? Id,
        [property: JsonPropertyName("snippet")] YouTubeSnippet? Snippet,
        [property: JsonPropertyName("contentDetails")] YouTubeChannelContent? ContentDetails);

    private sealed record YouTubePlaylistsResponse(
        [property: JsonPropertyName("items")] YouTubePlaylistDetail[] Items);

    private sealed record YouTubePlaylistDetail(
        [property: JsonPropertyName("snippet")] YouTubeSnippet? Snippet);
}
